/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.healthfirst.ui;

import com.assignment.healthfirst.models.AdministrationClass;
import com.assignment.healthfirst.models.ReportChartsClass;
import com.assignment.healthfirst.models.Validator;
import java.awt.HeadlessException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author zweli
 */
public class Adminfrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Adminfrm.class.getName());
    
    /**
     * Creates new form AdminWIthTabs
     */
    public Adminfrm() {
        initComponents();
        Loginfrm lgf = new Loginfrm();
        lgf.dispose();
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        try{
            AdministrationClass ac = new AdministrationClass();
            AdministrationClass.selectMedTable(tblMedicineManagement);
            ac.selectSupplierTable(tblSupplierTable);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabAdmin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        txtSearchMedID = new javax.swing.JTextField();
        btnMedSearch = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        btnAddMed = new javax.swing.JButton();
        btnUpdateMed = new javax.swing.JButton();
        btnDeleteMed = new javax.swing.JButton();
        txtCompany = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboxMedType = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSOH = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtReOrderLevel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicineManagement = new javax.swing.JTable();
        txtSupplierID = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        cboxDay = new javax.swing.JComboBox<>();
        cboxYear = new javax.swing.JComboBox<>();
        cboxMonth = new javax.swing.JComboBox<>();
        btnClearMed = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtsSupplierIDMain = new javax.swing.JTextField();
        btnSearchSupplier = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtSupplierNameMain = new javax.swing.JTextField();
        btnAddSuplier1 = new javax.swing.JButton();
        btnUpdateSuplier1 = new javax.swing.JButton();
        txtSupplierContactPerson = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        btnDeleteSuplier = new javax.swing.JButton();
        txtSupplierEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplierTable = new javax.swing.JTable();
        btnClearSupplier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        txtSearchUserID = new javax.swing.JTextField();
        txtSearchUser = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        cboxRole = new javax.swing.JComboBox<>();
        txtUserPassword = new javax.swing.JPasswordField();
        jLabel59 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        txtClear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jpTop5SellingItems = new javax.swing.JPanel();
        jpExpiryChart = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblExpiry = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jpSalesChart = new javax.swing.JPanel();
        jpLowStockChart = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLowStock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAdmin.setBackground(new java.awt.Color(182, 197, 194));
        tabAdmin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAdminMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(182, 197, 194));

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(97, 143, 114));
        jLabel36.setText("Med ID:");

        txtSearchMedID.setBackground(new java.awt.Color(97, 143, 114));
        txtSearchMedID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnMedSearch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnMedSearch.setForeground(new java.awt.Color(1, 26, 20));
        btnMedSearch.setText("Search");
        btnMedSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedSearch.addActionListener(this::btnMedSearchActionPerformed);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(97, 143, 114));
        jLabel15.setText("Name:");

        txtMedName.setBackground(new java.awt.Color(97, 143, 114));
        txtMedName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnAddMed.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnAddMed.setForeground(new java.awt.Color(1, 26, 20));
        btnAddMed.setText("List Product");
        btnAddMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddMed.addActionListener(this::btnAddMedActionPerformed);

        btnUpdateMed.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnUpdateMed.setForeground(new java.awt.Color(1, 26, 20));
        btnUpdateMed.setText("Update");
        btnUpdateMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateMed.addActionListener(this::btnUpdateMedActionPerformed);

        btnDeleteMed.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnDeleteMed.setText("Delete");
        btnDeleteMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteMed.addActionListener(this::btnDeleteMedActionPerformed);

        txtCompany.setBackground(new java.awt.Color(97, 143, 114));
        txtCompany.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(97, 143, 114));
        jLabel16.setText("Company:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(97, 143, 114));
        jLabel17.setText("Medicine Type:");

        cboxMedType.setBackground(new java.awt.Color(97, 143, 114));
        cboxMedType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboxMedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Tablet", "Capsule", "Syrup", "Injection", "Cream" }));

        txtPrice.setBackground(new java.awt.Color(97, 143, 114));
        txtPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtPrice.addActionListener(this::txtPriceActionPerformed);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(97, 143, 114));
        jLabel18.setText("Price:");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(97, 143, 114));
        jLabel19.setText("SOH:");

        txtSOH.setBackground(new java.awt.Color(97, 143, 114));
        txtSOH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSOH.addActionListener(this::txtSOHActionPerformed);

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(97, 143, 114));
        jLabel20.setText("Expiry Date:");

        txtReOrderLevel.setBackground(new java.awt.Color(97, 143, 114));
        txtReOrderLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tblMedicineManagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMedicineManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Name", "Company", "Medicine Type", "Price", "SOH", "Reorder Level", "Expiry Date", "Supplier ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedicineManagement);

        txtSupplierID.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel60.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(97, 143, 114));
        jLabel60.setText("Supplier Number:");

        jLabel61.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(97, 143, 114));
        jLabel61.setText("Re-Order Level:");

        cboxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cboxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        cboxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        btnClearMed.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnClearMed.setForeground(new java.awt.Color(1, 26, 20));
        btnClearMed.setText("Clear");
        btnClearMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearMed.addActionListener(this::btnClearMedActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSearchMedID, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnClearMed, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel61))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtReOrderLevel)
                                    .addComponent(txtMedName)
                                    .addComponent(txtCompany)
                                    .addComponent(cboxMedType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSOH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSupplierID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(cboxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddMed, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtSearchMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearMed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cboxMedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSOH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReOrderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateMed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteMed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabAdmin.addTab("Medicine Management", jPanel2);

        jPanel3.setBackground(new java.awt.Color(182, 197, 194));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(97, 143, 114));
        jLabel21.setText("Supplier ID:");

        txtsSupplierIDMain.setBackground(new java.awt.Color(97, 143, 114));
        txtsSupplierIDMain.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnSearchSupplier.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSearchSupplier.setForeground(new java.awt.Color(1, 26, 20));
        btnSearchSupplier.setText("Search");
        btnSearchSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchSupplier.addActionListener(this::btnSearchSupplierActionPerformed);

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(97, 143, 114));
        jLabel22.setText("Name:");
        jLabel22.setToolTipText("");

        txtSupplierNameMain.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierNameMain.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnAddSuplier1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnAddSuplier1.setForeground(new java.awt.Color(1, 26, 20));
        btnAddSuplier1.setText("Add Supplier");
        btnAddSuplier1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSuplier1.addActionListener(this::btnAddSuplier1ActionPerformed);

        btnUpdateSuplier1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnUpdateSuplier1.setForeground(new java.awt.Color(1, 26, 20));
        btnUpdateSuplier1.setText("Update");
        btnUpdateSuplier1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateSuplier1.addActionListener(this::btnUpdateSuplier1ActionPerformed);

        txtSupplierContactPerson.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierContactPerson.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(97, 143, 114));
        jLabel23.setText("Contact Person:");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(97, 143, 114));
        jLabel24.setText("Phone:");

        txtSupplierPhone.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierPhone.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnDeleteSuplier.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnDeleteSuplier.setForeground(new java.awt.Color(1, 26, 20));
        btnDeleteSuplier.setText("Delete");
        btnDeleteSuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteSuplier.addActionListener(this::btnDeleteSuplierActionPerformed);

        txtSupplierEmail.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(97, 143, 114));
        jLabel25.setText("Email:");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(97, 143, 114));
        jLabel26.setText("Address:");

        txtSupplierAddress.setBackground(new java.awt.Color(97, 143, 114));
        txtSupplierAddress.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        tblSupplierTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblSupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Name", "Contact Person", "Phone", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSupplierTable);

        btnClearSupplier.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnClearSupplier.setForeground(new java.awt.Color(1, 26, 20));
        btnClearSupplier.setText("Clear");
        btnClearSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSupplier.addActionListener(this::btnClearSupplierActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSupplierContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSupplierAddress)
                                        .addComponent(txtSupplierEmail)
                                        .addComponent(txtSupplierPhone)
                                        .addComponent(txtSupplierNameMain, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsSupplierIDMain, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClearSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateSuplier1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddSuplier1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtsSupplierIDMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnClearSupplier)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierNameMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddSuplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateSuplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabAdmin.addTab("Supplier Management", jPanel3);

        jPanel4.setBackground(new java.awt.Color(182, 197, 194));

        jLabel55.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(97, 143, 114));
        jLabel55.setText("User ID:");

        txtSearchUserID.setBackground(new java.awt.Color(97, 143, 114));
        txtSearchUserID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        txtSearchUser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtSearchUser.setText("Search");
        txtSearchUser.addActionListener(this::txtSearchUserActionPerformed);

        jLabel56.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(97, 143, 114));
        jLabel56.setText("Full Name:");

        txtFullname.setBackground(new java.awt.Color(97, 143, 114));
        txtFullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAddUser.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        txtUsername.setBackground(new java.awt.Color(97, 143, 114));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel57.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(97, 143, 114));
        jLabel57.setText("Username:");

        jLabel58.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(97, 143, 114));
        jLabel58.setText("Role:");

        cboxRole.setBackground(new java.awt.Color(97, 143, 114));
        cboxRole.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin", "Cashier" }));

        txtUserPassword.setBackground(new java.awt.Color(97, 143, 114));
        txtUserPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUserPassword.setText("jPasswordField1");

        jLabel59.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(97, 143, 114));
        jLabel59.setText("Password:");

        tblUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Role", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblUsers);

        txtClear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtClear.setText("Clear");
        txtClear.addActionListener(this::txtClearActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel59))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFullname)
                                    .addComponent(txtUsername)
                                    .addComponent(txtUserPassword)
                                    .addComponent(cboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSearchUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(txtSearchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchUser)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56))
                                .addGap(18, 18, 18)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel57))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59))))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabAdmin.addTab("User Management", jPanel4);

        jPanel6.setBackground(new java.awt.Color(182, 197, 194));
        jPanel6.setPreferredSize(new java.awt.Dimension(1089, 800));

        jpTop5SellingItems.setPreferredSize(new java.awt.Dimension(553, 363));

        javax.swing.GroupLayout jpTop5SellingItemsLayout = new javax.swing.GroupLayout(jpTop5SellingItems);
        jpTop5SellingItems.setLayout(jpTop5SellingItemsLayout);
        jpTop5SellingItemsLayout.setHorizontalGroup(
            jpTop5SellingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jpTop5SellingItemsLayout.setVerticalGroup(
            jpTop5SellingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpExpiryChart.setPreferredSize(new java.awt.Dimension(553, 363));

        tblExpiry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Med ID", "Name", "Day Before Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblExpiry);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Products Expirying Soon");

        javax.swing.GroupLayout jpExpiryChartLayout = new javax.swing.GroupLayout(jpExpiryChart);
        jpExpiryChart.setLayout(jpExpiryChartLayout);
        jpExpiryChartLayout.setHorizontalGroup(
            jpExpiryChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExpiryChartLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpExpiryChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jpExpiryChartLayout.setVerticalGroup(
            jpExpiryChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExpiryChartLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpSalesChart.setPreferredSize(new java.awt.Dimension(553, 363));

        javax.swing.GroupLayout jpSalesChartLayout = new javax.swing.GroupLayout(jpSalesChart);
        jpSalesChart.setLayout(jpSalesChartLayout);
        jpSalesChartLayout.setHorizontalGroup(
            jpSalesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jpSalesChartLayout.setVerticalGroup(
            jpSalesChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        jpLowStockChart.setPreferredSize(new java.awt.Dimension(553, 363));

        tblLowStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Med ID", "Name", "SOH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblLowStock);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Stock To Replenish");

        javax.swing.GroupLayout jpLowStockChartLayout = new javax.swing.GroupLayout(jpLowStockChart);
        jpLowStockChart.setLayout(jpLowStockChartLayout);
        jpLowStockChartLayout.setHorizontalGroup(
            jpLowStockChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLowStockChartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jpLowStockChartLayout.setVerticalGroup(
            jpLowStockChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLowStockChartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLowStockChart, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jpSalesChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTop5SellingItems, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jpExpiryChart, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpSalesChart, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jpTop5SellingItems, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpExpiryChart, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(jpLowStockChart, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Lifetime Report");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Report ", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabAdmin)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSOHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSOHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSOHActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void tabAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAdminMouseClicked
        // TODO add your handling code here:
        AdministrationClass ac = new AdministrationClass();      
        try{
            DefaultTableModel model = (DefaultTableModel) tblLowStock.getModel();
            DefaultTableModel modelEpiry = (DefaultTableModel) tblExpiry.getModel();
            modelEpiry.setRowCount(0);
            model.setRowCount(0);
            AdministrationClass.selectMedTable(tblMedicineManagement);
            AdministrationClass.selectUserTable(tblUsers);
            ac.salesReports(jpSalesChart,jpTop5SellingItems);
            ac.lowStockReorderReports(model);
            ac.expiryBatchReports(modelEpiry);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabAdminMouseClicked

    private void btnMedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedSearchActionPerformed
        // TODO add your handling code here:
        try{
            if (!txtSearchMedID.getText().equals("")) {
                String medID = txtSearchMedID.getText();

                AdministrationClass.searchMed(
                        medID,
                        tblMedicineManagement,
                        txtMedName,
                        txtCompany,
                        cboxMedType,
                        txtPrice,
                        txtSOH,
                        txtSupplierID,
                        txtReOrderLevel,
                        cboxDay,
                        cboxMonth,
                        cboxYear);
            } else {

                JOptionPane.showMessageDialog(null, "Product ID required!", "Message", JOptionPane.ERROR_MESSAGE);
                txtSearchMedID.isFocusable();
            }
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex, "Message", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnMedSearchActionPerformed

    
    private String medicine_id, name, company, medicine_type, supplier_id, expiry_date,day, month,year = null;
    private int quantity_in_stock, reorder_level =0;
    private double price = 0.0;
    private void btnAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedActionPerformed
                                   
        // TODO add your handling code here:
        try{
            
            if(!(cboxDay.getSelectedItem().equals(0) 
                   || cboxMonth.getSelectedItem().equals(0)  
                   || cboxYear.getSelectedItem().equals(0)  
                   || txtMedName.getText().isEmpty() 
                   || txtCompany.getText().isEmpty() 
                   || cboxMedType.getSelectedItem().equals(0) 
                   || txtSupplierID.getText().isEmpty() 
                   || txtSOH.getText().isEmpty() 
                   || txtReOrderLevel.getText().isEmpty() 
                   || txtPrice.getText().isEmpty())
                    ){
                if (!Validator.isValidDouble(txtPrice.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid price");
                    return;
                }

                if (!Validator.isValidInteger(txtSOH.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid stock value!");
                    return;
                }
                
                if (!Validator.isValidInteger(txtSupplierID.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Supplier number!");
                    return;
                }
                
                if (!Validator.isValidInteger(txtReOrderLevel.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Re-order value!");
                    return;
                }
                
                AdministrationClass ac = new AdministrationClass();

                day = cboxDay.getSelectedItem().toString();
                month = cboxMonth.getSelectedItem().toString();
                year = cboxYear.getSelectedItem().toString();

                medicine_id = txtSearchMedID.getText();
                name = txtMedName.getText();
                company = txtCompany.getText();
                medicine_type = cboxMedType.getSelectedItem().toString();
                supplier_id = txtSupplierID.getText();
                quantity_in_stock = Integer.parseInt(txtSOH.getText());
                reorder_level = Integer.parseInt(txtReOrderLevel.getText());
                price = Double.parseDouble(txtPrice.getText());
                expiry_date = year + "-" + day + "-" + month;

                ac.addMedicine(name,
                        medicine_type,
                        price,
                        quantity_in_stock,
                        reorder_level,
                        expiry_date,
                        company,
                        supplier_id);

                AdministrationClass.selectMedTable(tblMedicineManagement);
            }else{
                JOptionPane.showMessageDialog(null,"All fields required!", "Message", JOptionPane.ERROR_MESSAGE);
            
            }
        
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMedActionPerformed

    private void btnUpdateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedActionPerformed
        // TODO add your handling code here:
        
        try{
                        
            if (!(cboxDay.getSelectedItem().equals(0)
                    || cboxMonth.getSelectedItem().equals(0)
                    || cboxYear.getSelectedItem().equals(0)
                    || txtSearchMedID.getText().isEmpty()
                    || txtMedName.getText().isEmpty()
                    || txtCompany.getText().isEmpty()
                    || cboxMedType.getSelectedItem().equals(0)
                    || txtSupplierID.getText().isEmpty()
                    || txtSOH.getText().isEmpty()
                    || txtReOrderLevel.getText().isEmpty()
                    || txtPrice.getText().isEmpty())) {
                
                
                if (!Validator.isValidDouble(txtPrice.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid price, only numeric value required!");
                    return;
                }

                if (!Validator.isValidInteger(txtSOH.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid quantity, only numeric value required!");
                    return;
                }

                if (!Validator.isValidInteger(txtSupplierID.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Supplier number, only numeric value required!");
                    return;
                }
                
                if (!Validator.isValidInteger(txtReOrderLevel.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Re-order value, only numeric value required!");
                    return;
                }
                
                AdministrationClass ac = new AdministrationClass();

                day = cboxDay.getSelectedItem().toString();
                month = cboxMonth.getSelectedItem().toString();
                year = cboxYear.getSelectedItem().toString();

                medicine_id = txtSearchMedID.getText();
                name = txtMedName.getText();
                company = txtCompany.getText();
                medicine_type = cboxMedType.getSelectedItem().toString();
                supplier_id = txtSupplierID.getText();
                quantity_in_stock = Integer.parseInt(txtSOH.getText());
                reorder_level = Integer.parseInt(txtReOrderLevel.getText());
                price = Double.parseDouble(txtPrice.getText());
                expiry_date = year + "-" + month + "-" + day;

                ac.updateMedicine(medicine_id,
                        name,
                        medicine_type,
                        price,
                        quantity_in_stock,
                        reorder_level,
                        expiry_date,
                        company,
                        supplier_id);

                AdministrationClass.selectMedTable(tblMedicineManagement);
            } else {
                JOptionPane.showMessageDialog(null, "All fields required!", "Message", JOptionPane.ERROR_MESSAGE);

            }
   
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
          
        }
    }//GEN-LAST:event_btnUpdateMedActionPerformed

    private void btnDeleteMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedActionPerformed
        // TODO add your handling code here:
        try{
            
            if(!txtSearchMedID.getText().isEmpty()){
                AdministrationClass ac = new AdministrationClass();
                medicine_id = txtSearchMedID.getText();
                ac.removeMedicine(medicine_id);
                AdministrationClass.selectMedTable(tblMedicineManagement);
            }else{
                JOptionPane.showMessageDialog(null, "Product ID required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMedActionPerformed

    private void btnDeleteSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSuplierActionPerformed
        // TODO add your handling code here:
        try{
            
            if(!txtsSupplierIDMain.getText().isEmpty()){
                AdministrationClass ac = new AdministrationClass();

                supplier_id = txtsSupplierIDMain.getText();

                ac.removeSupplier(supplier_id);

                txtsSupplierIDMain.setText("");
                txtSupplierNameMain.setText("");
                txtSupplierContactPerson.setText("");
                txtSupplierPhone.setText("");
                txtSupplierEmail.setText("");
                txtSupplierAddress.setText("");

                ac.selectSupplierTable(tblSupplierTable);
            
            }else{
                JOptionPane.showMessageDialog(null, "All fields required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteSuplierActionPerformed

    private void btnSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSupplierActionPerformed
        // TODO add your handling code here:
        try{
            if(!txtsSupplierIDMain.getText().isEmpty() ){
                DefaultTableModel model = (DefaultTableModel) tblSupplierTable.getModel();
                model.setRowCount(0);
                AdministrationClass ac = new AdministrationClass();

                supplier_id = txtsSupplierIDMain.getText();

                ac.searchSupplier(
                        supplier_id,
                        tblSupplierTable,
                        txtSupplierNameMain,
                        txtSupplierContactPerson,
                        txtSupplierPhone,
                        txtSupplierEmail,
                        txtSupplierAddress);
            }else{
                JOptionPane.showMessageDialog(null, "Supplier ID required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex, "Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSearchSupplierActionPerformed
    String contact_person, phone, email,address;
    private void btnAddSuplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuplier1ActionPerformed
        // TODO add your handling code here:
        try{
            
            if(!(txtSupplierNameMain.getText().isEmpty()
                    || txtSupplierContactPerson.getText().isEmpty()
                    || txtSupplierPhone.getText().isEmpty()
                    || txtSupplierEmail.getText().isEmpty()
                    || txtSupplierAddress.getText().isEmpty())){
                
                
                AdministrationClass ac = new AdministrationClass();

                name = txtSupplierNameMain.getText();
                contact_person = txtSupplierContactPerson.getText();
                phone = txtSupplierPhone.getText();
                email = txtSupplierEmail.getText();
                address = txtSupplierAddress.getText();

                ac.addSupplier(name, contact_person, phone, email, address);
                ac.selectSupplierTable(tblSupplierTable);
            
            }else{
                JOptionPane.showMessageDialog(null, "Please fill in all fields!", "Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddSuplier1ActionPerformed

    private void btnUpdateSuplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSuplier1ActionPerformed
        // TODO add your handling code here:
            try{
    
                if (!(txtSupplierNameMain.getText().isEmpty()
                        || txtSupplierContactPerson.getText().isEmpty()
                        || txtSupplierPhone.getText().isEmpty()
                        || txtSupplierEmail.getText().isEmpty()
                        || txtSupplierAddress.getText().isEmpty())) {
                    
                    AdministrationClass ac = new AdministrationClass();
                    supplier_id = txtsSupplierIDMain.getText();
                    name = txtSupplierNameMain.getText();
                    contact_person = txtSupplierContactPerson.getText();
                    phone = txtSupplierPhone.getText();
                    email = txtSupplierEmail.getText();
                    address = txtSupplierAddress.getText();

                    ac.updateSupplier(supplier_id, name, contact_person, phone, email, address);
                    ac.selectSupplierTable(tblSupplierTable);

                } else {
                    JOptionPane.showMessageDialog(null, "All fields required!", "Message", JOptionPane.ERROR_MESSAGE);
                }
                
            }catch(HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnUpdateSuplier1ActionPerformed
    String username, password, role, full_name;
    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        try{
            
            if(!(txtUsername.getText().isEmpty() 
                    || txtFullname.getText().isEmpty()
                    || txtUserPassword.getText().isEmpty()
                    || cboxRole.getSelectedItem().equals(0))){
            
                AdministrationClass ac = new AdministrationClass();

                username = txtUsername.getText();
                full_name = txtFullname.getText();
                password = txtUserPassword.getText();
                role = cboxRole.getSelectedItem().toString();


                ac.addUser(username, password, role, full_name);
            
            }else{
                JOptionPane.showMessageDialog(null, "All fields are required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    String user_id;
    private void txtSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchUserActionPerformed
        // TODO add your handling code here:
        try{
            
            if(!txtSearchUserID.getText().isEmpty()){
                
                AdministrationClass ac = new AdministrationClass();

                user_id = txtSearchUserID.getText();

                ac.searchUser(user_id, txtUsername, txtUserPassword, cboxRole, txtFullname, tblUsers);
                
            }else{
            
                JOptionPane.showMessageDialog(null, "User ID required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchUserActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            if(!(txtUsername.getText().isEmpty()
                    || txtFullname.getText().isEmpty()
                    || txtUserPassword.getText().isEmpty()
                    || cboxRole.getSelectedItem().equals(0)))
            {
                AdministrationClass ac = new AdministrationClass();
                ac.updateUser(txtSearchUserID, txtUsername, txtUserPassword, cboxRole, txtFullname);
                AdministrationClass.selectUserTable(tblUsers);
               
            }else{
                JOptionPane.showMessageDialog(null, "All fields are required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            if(!txtSearchUserID.getText().isEmpty()){
                
                AdministrationClass ac = new AdministrationClass();
                user_id = txtSearchUserID.getText();
                ac.removeUser(user_id);

                AdministrationClass.selectUserTable(tblUsers);
            
            }else{
                JOptionPane.showMessageDialog(null, "User ID required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex,"Message", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

        txtSearchUserID.setText("");
        txtFullname.setText("");
        txtUsername.setText("");
        cboxRole.setSelectedIndex(0);
        txtUserPassword.setText("");

        model.setRowCount(0);
        
        AdministrationClass.selectUserTable(tblUsers);
    }//GEN-LAST:event_txtClearActionPerformed

    private void btnClearMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblMedicineManagement.getModel();
        
        txtSearchMedID.setText("");
        txtMedName.setText("");
        txtCompany.setText("");
        cboxMedType.setSelectedIndex(0);
        txtPrice.setText("");
        txtSOH.setText("");
        txtSupplierID.setText("");
        txtReOrderLevel.setText("");
        cboxDay.setSelectedIndex(0);
        cboxMonth.setSelectedIndex(0);
        cboxYear.setSelectedIndex(0);
        model.setRowCount(0);
        AdministrationClass.selectMedTable(tblMedicineManagement);
    }//GEN-LAST:event_btnClearMedActionPerformed

    private void btnClearSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSupplierActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblSupplierTable.getModel();
        AdministrationClass ac = new AdministrationClass();
        
        txtsSupplierIDMain.setText("");
        txtSupplierNameMain.setText("");
        txtSupplierContactPerson.setText("");
        txtSupplierPhone.setText("");
        txtSupplierEmail.setText("");
        txtSupplierAddress.setText("");
        model.setRowCount(0);
        ac.selectSupplierTable(tblSupplierTable);
    }//GEN-LAST:event_btnClearSupplierActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLowStock.getModel();
        DefaultTableModel modelEpiry = (DefaultTableModel) tblExpiry.getModel();
        modelEpiry.setRowCount(0);
        model.setRowCount(0);
        AdministrationClass ac = new AdministrationClass();
        ac.salesReports(jpSalesChart, jpTop5SellingItems);
        ac.lowStockReorderReports(model);
        ac.expiryBatchReports(modelEpiry);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            Loginfrm loginfrm = new Loginfrm();
            this.dispose();
            loginfrm.setVisible(true);

        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Adminfrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMed;
    private javax.swing.JButton btnAddSuplier1;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnClearMed;
    private javax.swing.JButton btnClearSupplier;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteMed;
    private javax.swing.JButton btnDeleteSuplier;
    private javax.swing.JButton btnMedSearch;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchSupplier;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateMed;
    private javax.swing.JButton btnUpdateSuplier1;
    private javax.swing.JComboBox<String> cboxDay;
    private javax.swing.JComboBox<String> cboxMedType;
    private javax.swing.JComboBox<String> cboxMonth;
    private javax.swing.JComboBox<String> cboxRole;
    private javax.swing.JComboBox<String> cboxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpExpiryChart;
    private javax.swing.JPanel jpLowStockChart;
    private javax.swing.JPanel jpSalesChart;
    private javax.swing.JPanel jpTop5SellingItems;
    private javax.swing.JTabbedPane tabAdmin;
    private javax.swing.JTable tblExpiry;
    private javax.swing.JTable tblLowStock;
    private javax.swing.JTable tblMedicineManagement;
    private javax.swing.JTable tblSupplierTable;
    private javax.swing.JTable tblUsers;
    private javax.swing.JButton txtClear;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReOrderLevel;
    private javax.swing.JTextField txtSOH;
    private javax.swing.JTextField txtSearchMedID;
    private javax.swing.JButton txtSearchUser;
    private javax.swing.JTextField txtSearchUserID;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierContactPerson;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierNameMain;
    private javax.swing.JTextField txtSupplierPhone;
    private javax.swing.JPasswordField txtUserPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtsSupplierIDMain;
    // End of variables declaration//GEN-END:variables
}
