/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.healthfirst.ui;

import com.assignment.healthfirst.models.BillingClass;
import com.assignment.healthfirst.models.CashierClass;
import java.awt.HeadlessException;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zweli
 */
public class point_of_sale_frm extends javax.swing.JFrame {
    public ArrayList<BillingClass> cart = new ArrayList<>();
    BillingClass billing;
    BillingClass item = new BillingClass();
    public static double totalAmount = 0.0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(point_of_sale_frm.class.getName());
    
    /**
     * Creates new form point_of_sale_frm
     */
    public point_of_sale_frm() {
        initComponents();
        setLocationRelativeTo(null);
        btnCheckOut.setEnabled(false);
        btnAddToCart.setEnabled(false);
        setResizable(false);
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMedicineID_Dispaly = new javax.swing.JTextField();
        txtMedicineName = new javax.swing.JTextField();
        txtMedicineType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMedicineID = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        btnClearCart = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnLookUp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 143, 114));

        tblCart.setBackground(new java.awt.Color(182, 197, 194));
        tblCart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblCart.setForeground(new java.awt.Color(1, 26, 20));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Med ID", "Name", "Medicine Type", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);

        jPanel2.setBackground(new java.awt.Color(1, 26, 20));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 162, 126));
        jLabel1.setText("Medicine ID:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 162, 126));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 162, 126));
        jLabel3.setText("Price:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 162, 126));
        jLabel4.setText("Medicine Type:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 162, 126));
        jLabel5.setText("Quantity:");

        txtMedicineID_Dispaly.setEditable(false);
        txtMedicineID_Dispaly.setBackground(new java.awt.Color(115, 162, 126));
        txtMedicineID_Dispaly.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMedicineID_Dispaly.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMedicineID_Dispaly.setFocusable(false);
        txtMedicineID_Dispaly.setSelectionColor(new java.awt.Color(97, 143, 114));

        txtMedicineName.setEditable(false);
        txtMedicineName.setBackground(new java.awt.Color(115, 162, 126));
        txtMedicineName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMedicineName.setFocusable(false);
        txtMedicineName.setSelectionColor(new java.awt.Color(97, 143, 114));

        txtMedicineType.setEditable(false);
        txtMedicineType.setBackground(new java.awt.Color(115, 162, 126));
        txtMedicineType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMedicineType.setFocusable(false);
        txtMedicineType.setSelectionColor(new java.awt.Color(97, 143, 114));

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(115, 162, 126));
        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrice.setFocusable(false);
        txtPrice.setSelectionColor(new java.awt.Color(97, 143, 114));

        txtQuantity.setBackground(new java.awt.Color(182, 197, 194));
        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQuantity.setSelectionColor(new java.awt.Color(97, 143, 114));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(115, 162, 126));
        jLabel8.setText("Enter Medicine ID:");

        txtMedicineID.setBackground(new java.awt.Color(182, 197, 194));
        txtMedicineID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMedicineID.setSelectionColor(new java.awt.Color(97, 143, 114));

        btnAddToCart.setBackground(new java.awt.Color(182, 197, 194));
        btnAddToCart.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        btnClearCart.setBackground(new java.awt.Color(182, 197, 194));
        btnClearCart.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnClearCart.setText("Clear Cart");
        btnClearCart.addActionListener(this::btnClearCartActionPerformed);

        btnCheckOut.setBackground(new java.awt.Color(182, 197, 194));
        btnCheckOut.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnCheckOut.setText("Check Out");
        btnCheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckOut.addActionListener(this::btnCheckOutActionPerformed);

        btnLookUp.setBackground(new java.awt.Color(182, 197, 194));
        btnLookUp.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLookUp.setText("Look Up");
        btnLookUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLookUp.addActionListener(this::btnLookUpActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedicineID_Dispaly)
                                    .addComponent(txtMedicineName)
                                    .addComponent(txtMedicineType)
                                    .addComponent(txtPrice)
                                    .addComponent(txtMedicineID, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMedicineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLookUp)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMedicineID_Dispaly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClearCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckOut)
                .addGap(9, 9, 9))
        );

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 26, 20));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Amount:");

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setBackground(new java.awt.Color(97, 143, 114));
        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtTotalAmount.setText("R0,0");
        txtTotalAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtTotalAmount.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Back");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        try{
            if (!(txtMedicineName.getText().isEmpty()
                    || txtMedicineType.getText().isEmpty()
                    || txtPrice.getText().isEmpty()
                    || txtQuantity.getText().isEmpty())) {

                String medID;
                String medType;
                Double price;
                int qty;
                String name;

                medID = txtMedicineID.getText();
                name = txtMedicineName.getText();
                medType = txtMedicineType.getText();
                price = Double.valueOf(txtPrice.getText());
                qty = Integer.parseInt(txtQuantity.getText());
                billing = new BillingClass(name);

                billing.setMedID(medID);
                billing.setName(name);
                billing.setMedType(medType);
                billing.setPrice(price);
                billing.setQty(qty);

                cart.add(billing);

                DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
                model.addRow(new Object[]{billing.getMedID(),
                    billing.getName(),
                    billing.getMedType(),
                    billing.getPrice(),
                    billing.getQty()});

                NumberFormat currencyFormat = NumberFormat.getCurrencyInstance();

                for (BillingClass items : cart) {

                    totalAmount += items.getPrice() * items.getQty();
                }

                txtTotalAmount.setText(currencyFormat.format(totalAmount));
                btnCheckOut.setEnabled(true);


            } else {
                JOptionPane.showMessageDialog(null, "Please ensure no data is removed from the fields!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        
        }catch(HeadlessException | NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex,"Message",JOptionPane.ERROR_MESSAGE);       
        
        }
        
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        point_of_sale_frm posSelect3 = new point_of_sale_frm();
        posSelect3.setVisible(true);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        Posfrm posSelect = new Posfrm();
        posSelect.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?","Confirm Logout",
        JOptionPane.YES_NO_OPTION);
        
        if(response == JOptionPane.YES_OPTION){
            Loginfrm posSelect = new Loginfrm();
            posSelect.setVisible(true);
            this.dispose();
        }else{
            this.setVisible(true);
        }
        
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:
        Posfrm posSelect = new Posfrm();
        posSelect.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void btnLookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookUpActionPerformed
        // TODO add your handling code here:  
        try{
            if(!txtMedicineID.getText().equals("")){
                if(!txtQuantity.getText().equals("")){
                    
                    CashierClass cc = new CashierClass();                  
                    
                    String medID = txtMedicineID.getText();
                    int qty = Integer.parseInt(txtQuantity.getText());
                    if(!cc.checkStockAvailability(qty, medID)){
                        JOptionPane.showMessageDialog(null, "Over-selling product, you have "+cc.getavailableSOH()+" SOH left, please replenish!", "Message", JOptionPane.ERROR_MESSAGE);
                    }else{
                        cc.cashier(medID, qty);
                        txtMedicineID_Dispaly.setText(cc.getMedID());
                        txtMedicineName.setText(cc.getMedName());
                        txtMedicineType.setText(cc.getMedType());
                        double price = cc.getPrice();
                        txtPrice.setText(String.valueOf(price));
                        btnAddToCart.setEnabled(true);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Quantity required!", "Message", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Medicine ID required!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex, "Message", JOptionPane.ERROR_MESSAGE);
        
        }
       
    }//GEN-LAST:event_btnLookUpActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        txtMedicineID.setText("");
        txtQuantity.setText("");
        txtMedicineID_Dispaly.setText("");
        txtMedicineName.setText("");
        txtMedicineType.setText("");
        txtPrice.setText("");
        txtTotalAmount.setText("R0,0");
        model.setRowCount(0);
        totalAmount = 0.0;
        item.setPrice(0.0);
        item.setQty(0);
        cart.clear();
        btnAddToCart.setEnabled(false);
        btnCheckOut.setEnabled(false);
        
        
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:  
        try{
            
            String medID = txtMedicineID.getText();
            int qty = Integer.parseInt(txtQuantity.getText());

            CashierClass cashier = new CashierClass();
            cashier.setMedID(medID);
            cashier.setQuantity(qty);
            cashier.sale();
            Billingfrm bill = new Billingfrm(cart);
            bill.setVisible(true);
//            item.setPrice(0.0);
//            item.setQty(0);
            cart.clear();
            btnAddToCart.setEnabled(false);
            btnCheckOut.setEnabled(false);
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex, "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new point_of_sale_frm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnLookUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtMedicineID;
    private javax.swing.JTextField txtMedicineID_Dispaly;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
